In [ ]:
# Numpy 연습장

데이터 분석을 위한 기본적인 Numpy 예제를 알아봅시다!

In [ ]:
## 1. Numpy 사용하기
소스코드 최상단에 아래와 같이 입력합니다. 보통 np를 약자로 사용합니다.

In [1]:
import numpy as np

In [ ]:
arr = np.array(list)
type(arr)

numpy.ndarray

In [ ]:
## 2. Numpy 배열 만들기
Numpy 배열은 데이터 분석에서 가장 많이 사용되는 배열 중 하나입니다.<br>
크게 벡터(vector)와 매트릭스(matrix)로 나눌 수 있습니다.<br>

 - 벡터: 1차원 배열
 - 매트릭스: 2차원 배열(1차원만 사용 가능)

In [3]:
# [1,2,3,4,5]

# [ [1,2,3,4], [2,3,4,5], [5,6,7,8]]

In [ ]:

배열을 생성하는 방법은 여러가지가 있습니다. 

    1. 파이썬 리스트 이용: np.array([list])
    2. 0또는 1로 채우기: np.zeros(), np.ones()
    3. 일정한 간격을 가지는 숫자 배열: np.arange()
    4. 일정 범위 안에서 일정 갯수를 가진 배열: np.linspace()
    5. 랜덤 값을 가지는 배열: np.random.rand() / randint() / randn()

In [ ]:
### np.array()

In [18]:
result = []
for number in list_array:
    number = number * 10
    result.append(number)   

In [19]:
result

[10, 20, 30, 40, 50]

In [20]:
type(list_array)

list

In [ ]:
### arr = numpy.array(list_array)
arr = np.array(list_array)
### np numpy 라는 뜻 numpy에 array를 사용하는 것
arr

In [21]:
type(arr)

numpy.ndarray

In [22]:
# 2차원 배열 = 매트릭스
mat = [[1,2],[3,4]]
mat

[[1, 2], [3, 4]]

In [23]:
m_arr = np.array(mat)
m_arr

array([[1, 2],
       [3, 4]])

In [ ]:
# [실습 1]  
[0, 1, 2]와 [3, 4, 5]를 행으로 갖는 2차원 ndarray를 만들고, new_arr 변수에 저장합니다.

In [24]:
np.array([[0, 1, 2],[3, 4, 5]])
### numpy에서는 축에 대한 개념이 중요하다

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
### np.zeros() / np.ones()

In [26]:
# 모든 요소가 0 값을 가지는 배열 생성
np.zeros(4)

array([0., 0., 0., 0.])

In [27]:
np.zeros((5,5))
### numpy 에서는 세로의 개념이 먼저이다. (세로,가로)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
# 모든 요소가 1 값을 가지는 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# [실습 2]  
숫자 0으로 채워진 3x4 ndarray를 만들어 봅니다. 

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
### np.arange()

In [31]:
list(range(10)) # 0부터 시작 10까지 숫자를 가져와라 0 <= x < 10

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
# 0부터 10까지, 간격 1을 가지는 배열
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# 0부터 10까지, 간격 2를 가지는 배열
np.arange(0, 11, 2) # -> 0 <= x < 11 / 2

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# [실습 3]  
5부터 15까지, 간격 3을 가지는 ndarray를 만들어 봅니다. 

In [34]:
np.arange(5,15,3)

array([ 5,  8, 11, 14])

In [ ]:
### np.random.rand() / np.random.randn() / np.random.randint()

In [36]:
# 0과 1범위 내의 연속 균등 분포(uniform)에서 랜덤으로 값을 가져와 생성
np.random.rand(5)

array([0.58229025, 0.60392153, 0.47638719, 0.350612  , 0.1730227 ])

In [37]:
np.random.rand(5,5)

array([[0.3380806 , 0.48414695, 0.40573051, 0.96768317, 0.96181668],
       [0.95740171, 0.36401538, 0.44888627, 0.81693963, 0.18505171],
       [0.23923022, 0.48856952, 0.16849062, 0.60644702, 0.86775226],
       [0.8859067 , 0.86764172, 0.59873383, 0.3915061 , 0.33288519],
       [0.66631223, 0.2795236 , 0.28771015, 0.842695  , 0.41717302]])

In [20]:
# 표준 정규 분포(standard normal)에서 랜덤으로 값을 가져와 생성
np.random.randn(5,5)

array([[-1.46139238, -0.55183202,  1.85599546,  0.22451776,  0.93008971],
       [ 0.69996286, -0.95607511,  0.5615816 , -1.66137236, -1.23913789],
       [-0.08360373, -1.37668648,  0.28557869, -0.337403  ,  1.53713656],
       [-0.08231119,  0.71092725, -0.36498002, -0.99941128,  1.3684696 ],
       [ 0.9108686 ,  0.13283211, -0.74797875, -0.75939018,  0.52868564]])

In [39]:
# 특정 범위 내에서 랜덤 정수형 숫자(int)를 가져와 생성
np.random.randint(1,1000)

209

In [38]:
np.random.randint(1,1000, 5)

array([ 64, 465, 303, 194,  34])

In [ ]:
## 3. 배열의 연산

    1. 파이썬 리스트 연산과 비교
    2. 브로드캐스팅
    3. 연산속도 

In [26]:
temp_list = list(range(10))
temp_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
# 설명을 위해 의도적으로 발생시킨 오류입니다
temp_list + 7

TypeError: can only concatenate list (not "int") to list

In [28]:
np.arange(0, 11) + 7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [29]:
m_arr 

array([[1, 2],
       [3, 4]])

In [31]:
m_arr + m_arr

array([[2, 4],
       [6, 8]])

In [32]:
m_arr + [10, 20]

array([[11, 22],
       [13, 24]])

In [33]:
m_arr + 10

array([[11, 12],
       [13, 14]])

In [ ]:
### 연산 속도

In [34]:
big_data = np.arange(10000000)
len(big_data)

10000000

In [38]:
%%time
add_result = []
for num in big_data:
    add_result.append(num+10)
print(np.array(add_result))

[      10       11       12 ... 10000007 10000008 10000009]
Wall time: 3.59 s


In [39]:
%%time
big_data+10

Wall time: 11.5 ms


array([      10,       11,       12, ..., 10000007, 10000008, 10000009])

In [ ]:
# [실습 4]  
여러 가지 배열 연산에 대해서 실습합니다.

In [60]:
test_arr = np.arange(12).reshape(3, 4)
test_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# test_arr의 모든 원소에 숫자 3을 더합니다. 


In [ ]:
# test_arr의 모든 원소에 숫자 3을 뺍니다. 


In [ ]:
# test_arr의 모든 원소에 숫자 3을 곱합니다. 


In [ ]:
# test_arr의 모든 원소에 숫자 3으로 나눕니다. 


In [ ]:
## 4. 배열 요소 접근 및 범위 선택

    1. 배열 요소 접근 방식은 파이썬 리스트와 동일합니다.
    2. 범위 접근자(:) 사용 시 범위에 주의합시다 ( 1:5 는 1부터 4까지를 의미 )
    3. 배열 복사(메모리 문제 방지): XXX.copy()
    4. 특정 조건에 해당하는 데이터 선택은 인덱스를 사용합니다

In [43]:
arr = np.array([[1,3,5], [7,9,11], [2,4,6], [8,10,12]])
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [44]:
arr[0]

array([1, 3, 5])

In [50]:
arr[0:3]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6]])

In [49]:
arr[0, 1]
# 세로 0번째 가로 1번째

3

In [51]:
arr[:]
# 끝까지

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [129]:
arr[:, 1:]

array([[ 3,  5],
       [ 9, 11],
       [ 4,  6],
       [10, 12]])

In [59]:
arr

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [60]:
arr2 = arr.copy()

In [62]:
# 특정값 바꾸기
arr2[0, 0] = 10
arr2

array([[10,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

# [실습 5]  
test_arr 배열에 대하여 문제를 풀어봅니다.

test_arr

In [62]:
# 인덱스 1에 해당하는 데이터를 추출합니다. 


In [ ]:
# 인덱스 1부터 2까지 해당하는 데이터를 추출합니다. 


In [ ]:
# 인덱스 (2, 3)에 해당하는 데이터를 추출합니다. 


In [ ]:
## 5. 배열 다루기
데이터 분석 수행 시 배열을 쪼개고, 합쳐야 할 때를 빈번하게 마주칩니다.<br>
또한, 배열의 자료형이 맞지 않아 특정 기능을 실행할 수 없는 경우도 발생합니다.<br>
이러한 작업을 하려면 우선 numpy 자료형의 모양을 확인하고, <br>
필요하다면 원하는 모양으로 변환하는 과정이 필요하죠. 

In [ ]:
### 배열의 모양 확인하고 변경하기

    1. 배열 모양 확인: XXX.shape() 
    2. 배열 내의 데이터 자료형 확인: XXX.dtype
    3. 배열 모양 변경: XXX.reshape()
    4. 데이터 타입 변경: XXX.astype()
    
※ 배열 모양은 (row x col) 형태로 표현됩니다

In [74]:
arr = np.array([[1,2,3],[4,5,6],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [75]:
#배열 모양 확인
arr.shape

(3, 3)

In [72]:
## array의 차원 출력
arr.ndim

2

In [76]:
arr.size

9

In [77]:
arr.dtype

dtype('int32')

In [78]:
arr = np.array([[1,2,3],[4,5,6]], dtype='float')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [72]:
arr.dtype

dtype('float64')

In [73]:
arr2 = np.array(['1','2','3'])
arr2

array(['1', '2', '3'], dtype='<U1')

In [74]:
arr2.dtype

dtype('<U1')

In [ ]:
# [실습 6]  
m_arr 배열의 ndim, shape, size, dtype을 확인하고 그 결과를 살펴봅니다.

In [79]:
m_arr

array([[1, 2],
       [3, 4]])

In [ ]:
### np.reshape()

In [80]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [81]:
arr.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

arr.reshape(6,1)

In [83]:
arr.reshape(1, 6)

array([[1., 2., 3., 4., 5., 6.]])

In [84]:
arr.reshape(-1)

array([1., 2., 3., 4., 5., 6.])

In [85]:
arr.reshape(-1, 3)
# 배열이 클 때 정확한 배열의 구조를 모르겠을때 -1으로 정의해준다.
# -1은 정의하지 않겠다는 뜻 (열만 3개)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [86]:
arr.reshape(-1, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
# [실습 7]  
다음 배열을 (28, 28, 3) 형태로 변경합니다.

In [85]:
arr = np.random.randint(0, 10, size=2352)
arr.shape

(2352,)

In [ ]:
### 배열 쪼개고 / 합치기
일반적으로, 데이터 분석에서 다루는 모든 자료는 2차원 배열입니다.<br>
배열의 열 또는 행을 기준으로 데이터를 쪼개고 합치는 방법이 기본이며,<br>
가끔 특정 '조건'에 해당하는 열 또는 행에 대해 연산을 할 줄도 알아야 합니다.

In [87]:
# arr1 = 5x5 array
# arr2 = 3x1 array
# arr3 = 3x1 array

arr1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
arr2 = np.zeros(3)
arr3 = np.ones(2)

print(arr1)
print(arr2)
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[0. 0. 0.]
[1. 1.]


In [ ]:
### np.concatenate()

In [88]:
arr2

array([0., 0., 0.])

In [89]:
arr3

array([1., 1.])

In [93]:
# 1차원 배열 합치기
con = np.concatenate((arr2, arr3), axis=0)
print(con.shape)
con

(5,)


array([0., 0., 0., 1., 1.])

In [94]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [96]:
# row 기준으로 합치기
con2 = np.concatenate((arr1, arr1), axis=0)
print(con2.shape)
con2

(10, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [97]:
# col 기준으로 합치기
con3 = np.concatenate((arr1, arr1), axis=1)
print(con3.shape)
con3

(5, 4)


array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [ ]:
# [실습 8]  
다음 에러의 원인을 생각해보고, 해결해 보세요!

In [99]:
rst = np.concatenate((arr1, con), axis=1)
rst.shape

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [102]:
# # col을 기준으로 합치려면 reshape이 필요
# print(arr1.shape)
# print(con.shape)
# con = con.reshape(5,1)
# con

In [103]:
# # col 기준으로 합치기
# rst = np.concatenate((arr1, con), axis=1)
# rst

In [ ]:
### 마스킹 연산 - 조건에 맞는 데이터 처리

In [104]:
rst = con3.copy()
rst

array([[ 1,  2,  1,  2],
       [ 3,  4,  3,  4],
       [ 5,  6,  5,  6],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [105]:
rst > 5

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [117]:
rst[rst > 5]

array([ 6,  6,  7,  8,  7,  8,  9, 10,  9, 10])

In [118]:
rst[:, 2] < 5

array([ True,  True, False, False, False])

In [120]:
rst[rst[:, 2] < 5]

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [121]:
rst[1] == 3

array([ True, False,  True, False])

In [122]:
rst[:, rst[1]==3]

array([[1, 1],
       [3, 3],
       [5, 5],
       [7, 7],
       [9, 9]])

In [ ]:
# [실습 9]  
rst에서 짝수에 해당하는 값을 추출합니다. (힌트: 나머지를 구하는 파이썬 % 연산자 활용)